# specify the node base image with your desired version node:<version>
FROM node:alpine


WORKDIR /var/www

# replace this with your application's default port
ARG NODE_EXPOSE=8888
EXPOSE ${NODE_EXPOSE}}